const uiText = {
  ta: {
    home: "முகப்பு",
    search: "தேடல்",
    settings: "அமைப்புகள்",
    keywords: "தமிழ் வேதாகமம், வேதாகமம் தமிழ், தமிழ் கிறிஸ்தவ ஆப், வேதாகம வசனங்கள், Tanglish Bible search, Tamil scripture, Tamil Bible online, Tamil Bible reading, Bible study Tamil, Tamil Bible study tools, Tamil Bible Premium, Tamil Bible Presentation, Church Bible Display Tamil",
    tamilBible: "தமிழ் வேதாகமம்",
    richReader: "ஆழமான இருண்ட வாசிப்பு அனுபவம்",
    homeIntro:
      "ஏற்பாட்டைத் தேர்ந்தெடுத்து, புத்தகத்தைத் திறந்து, மொபைல் மற்றும் டெஸ்க்டாப் இரண்டிலும் அமைதியான வாசிப்பைத் தொடங்குங்கள்.",
    tanglishSearch: "Tanglish தேடல்",
    mobileFriendly: "மொபைல் தோற்றம்",
    readerSettings: "வாசிப்பு அமைப்புகள்",
    library: "நூலகம்",
    chooseStart: "தேர்ந்தெடுத்து வாசிக்க தொடங்குங்கள்",
    books: "புத்தகங்கள்",
    testament: "ஏற்பாடு",
    oldTestament: "பழைய ஏற்பாடு",
    newTestament: "புதிய ஏற்பாடு",
    oldDesc: "வரலாறு, தீர்க்கதரிசனம், சங்கீதம், ஞான வாசகம்",
    newDesc: "சுவிசேஷம், அப்போஸ்தலர், கடிதங்கள், வெளிப்படுத்தல்",
    globalSearch: "முழு தேடல்",
    searchTitle: "புத்தகம், வசனம், Tanglish அனைத்தும் ஒரே இடத்தில்",
    searchIntro:
      "புத்தகப் பெயர் மற்றும் வசனங்களை தமிழ், ஆங்கிலம், அல்லது Tanglish மூலம் தேடலாம்.",
    searchPlaceholder: "புத்தகம் அல்லது வசனம் தேடு...",
    verses: "வசனங்கள்",
    typeToSearch:
      "புத்தகம், வசனம், அல்லது Tanglish சொற்றொடரைத் தட்டச்சு செய்து தேடத் தொடங்குங்கள்.",
    chapters: "அதிகாரங்கள்",
    selectChapter: "வாசிப்பைத் தொடர ஒரு அதிகாரத்தைத் தேர்ந்தெடுக்கவும்.",
    reading: "வாசிப்பு",
    navigator: "வழிகாட்டி",
    chapter: "அதிகாரம்",
    verse: "வசனம்",
    prev: "முந்தையது",
    next: "அடுத்தது",
    share: "பகிர்",
    close: "மூடு",
    cancel: "ரத்து செய்",
    save: "சேமி",
    readingSetup: "வாசிப்பு அமைப்பு",
    settingsTitle: "அமைப்புகள்",
    settingsIntro:
      "எழுத்தளவு, இடைவெளி, தோற்றம், மற்றும் UI மொழியை உங்கள் விருப்பத்துக்கு மாற்றுங்கள்.",
    resetSettings: "மீட்டமை",
    typography: "எழுத்தமைப்பு",
    typographyIntro: "வாசிப்பை மென்மையாகவும் தெளிவாகவும் மாற்றுங்கள்.",
    advancedPresentation: "அட்வான்ஸ் பிரெஸன்டேஷன்",
    advancedPresentationIntro: "OBS, stage screen, casting, and presentation view controls.",
    screenSetup: "ஸ்க்ரீன் அமைப்பு",
    enableMainPresentation: "மெயின் பிரெஸன்டேஷன் ஆன்",
    enableStagePresentation: "ஸ்டேஜ் பிரெஸன்டேஷன் ஆன்",
    mainPresentationScreen: "மெயின் பிரெஸன்டேஷன் ஸ்க்ரீன்",
    stageviewScreen: "ஸ்டேஜ்வியூ ஸ்க்ரீன்",
    mainPresentationScreenSetup: "மெயின் பிரெஸன்டேஷன் ஸ்க்ரீன் அமைப்பு",
    stageviewScreenSetup: "ஸ்டேஜ்வியூ ஸ்க்ரீன் அமைப்பு",
    presets: "பிரீசெட்ஸ்",
    maximumFontSize: "அதிகபட்ச எழுத்தளவு",
    stageScreenStyle: "ஸ்டேஜ் ஸ்க்ரீன் ஸ்டைல்",
    windowView: "Window View",
    smallWindow: "Small Window",
    greenScreen: "Green Screen",
    message: "மெசேஜ்",
    showMessage: "Show Message",
    clearMessage: "Clear Message",
    previewPanel: "Preview",
    backgroundImage: "Background Image",
    logoImage: "Logo Image",
    motionBackground: "Motion Background",
    stillBackground: "Still Background",
    textColor: "Text Color",
    overlayColor: "Overlay Color",
    screenOne: "Screen 1 → 1536x864",
    screenTwo: "Screen 2 → 1920x1080",
    fullScreenHorizontal: "Full screen - Horizontal",
    fullScreenPrimary: "Full Screen - Primary",
    enableTransition: "Enable Transition",
    enableOutline: "Enable Outline",
    enableShadow: "Enable Shadow",
    enableUppercase: "Enable Uppercase",
    enableBorder: "Enable Border",
    enableBox: "Enable Box",
    enableHeaderBox: "Enable Header Box",
    enableLineWrap: "Enable Line Wrap",
    hideStanzaNumber: "Hide Stanza Number",
    showLyricsInTwoLines: "Show Verse in Two Lines",
    keepPresentationWindowOnTop: "Keep Presentation Window on Top",
    showDateAndTime: "Show Date and Time",
    showVerseviewLogo: "Show Tamil Bible Premium Logo",
    showCustomLogo: "Show Custom Logo",
    uploadLogo: "Upload Logo",
    removeLogo: "Remove Logo",
    textOne: "Text 1",
    textTwo: "Text 2",
    overlay: "Overlay",
    stars: "Stars",
    waves: "Waves",
    particles: "Particles",
    aurora: "Aurora",
    embers: "Embers",
    halo: "Halo",
    mist: "Mist",
    fontSize: "எழுத்தளவு",
    lineSpacing: "வரி இடைவெளி",
    textAlign: "உரை சீரமைப்பு",
    readingCard: "வாசிப்பு அட்டை",
    readingCardIntro: "பின்னணியில் அட்டையின் இருள் அளவைத் தேர்ந்தெடுக்கவும்.",
    cardOpacity: "அட்டை தெளிவு",
    readerWidth: "வாசிப்பு அகலம்",
    showReference: "வசன குறிப்பைக் காட்டு",
    yes: "ஆம்",
    no: "இல்லை",
    customBackground: "தனிப்பயன் பின்னணி",
    customBackgroundIntro: "உங்கள் சொந்த படத்தை reader பின்னணியாக பயன்படுத்துங்கள்.",
    imageUrl: "பட இணைப்பு",
    useImageLink: "இணைப்பை பயன்படுத்து",
    uploadImage: "படத்தை ஏற்று",
    removeImage: "படத்தை அகற்று",
    applyNow: "உடனே பயன்படுத்து",
    livePreview: "நேரடி முன்னோட்டம்",
    previewVerse: "கர்த்தர் என் மேய்ப்பராயிருக்கிறார், நான் தாழ்ச்சியடையேன்",
    previewVerseEnglish: "The Lord is my shepherd; I shall not want.",
    previewRef: "சங்கீதம் 23:1",
    installApp: "ஆப்பாக நிறுவு",
    installAppIntro: "இந்த தளத்தை மொபைல் அல்லது கணினியில் தனி software போல நிறுவலாம்.",
    installNow: "இப்போது நிறுவு",
    installed: "ஏற்கனவே நிறுவப்பட்டுள்ளது",
    installHelp:
      "உங்கள் browser menu-இல் Install App அல்லது Add to Home Screen தேர்வு செய்யலாம்.",
    installBannerTitle: "இந்த வேதாகமத்தை ஆப்பாக சேமிக்கவும்",
    installBannerText:
      "முகப்புத்திரையில் நிறுவி, software போல வேகமாகத் திறக்கலாம்.",
    imageBackgrounds: "படப் பின்னணி",
    imageBackgroundsIntro: "Reader க்கு படப் பின்னணி தேர்வு செய்யுங்கள்.",
    motionBackgroundsIntro: "நகரும் பின்னணி தோற்றத்தை தேர்வு செய்யுங்கள்.",
    gradientBackgrounds: "நிற சரிவு பின்னணி",
    gradientBackgroundsIntro: "சிறிய, மென்மையான reader பின்னணி.",
    language: "மொழி",
    languageIntro: "நாவ்பார் மற்றும் UI எழுத்துகளின் மொழி.",
    tamil: "தமிழ்",
    english: "ஆங்கிலம்",
    tamilEnglish: "தமிழ் + English",
    left: "இடப்பு",
    center: "மையம்",
    justify: "இருபுறம்",
    openBook: "புத்தகத்தைத் திற",
    verseOfDay: "இன்றைய வசனம்",
    recentReading: "சமீபத்திய வாசிப்பு",
    bookmarksTitle: "புக் மார்க்கள்",
    favoritesTitle: "பிடித்தவை",
    highlightsTitle: "ஹைலைட்கள்",
    notesTitle: "குறிப்புகள்",
    noItemsYet: "இங்கு இன்னும் ஒன்றும் இல்லை.",
    bookmark: "புக் மார்க்",
    favorite: "பிடித்தது",
    highlight: "ஹைலைட்",
    autoScroll: "ஆட்டோ ஸ்க்ரோல்",
    pauseScroll: "ஸ்க்ரோல் நிறுத்து",
    note: "குறிப்பு",
    chapterBookmark: "அதிகாரம் புக் மார்க்",
    notePrompt: "இந்த வசனத்திற்கான உங்கள் குறிப்பை எழுதுங்கள்.",
    openVerse: "வசனத்தைத் திற",
    openChapter: "அதிகாரத்தைத் திற",
    savedNote: "சேமிக்கப்பட்ட குறிப்புகள்",
    savedHighlight: "ஹைலைட் வசனங்கள்",
    savedFavorite: "பிடித்த வசனங்கள்",
    savedBookmark: "சேமித்த இடங்கள்",
    presentation: "காட்சி அமைப்பு",
    stageView: "சபை திரை",
    mainDisplay: "முக்கிய திரை",
    stageDisplay: "சபை திரை அமைப்பு",
    enableMainDisplay: "முக்கிய திரையை இயக்கு",
    enableStageDisplay: "சபை திரையை இயக்கு",
    screenChoice: "திரையைத் தேர்ந்தெடு",
    maxFontSize: "அதிகபட்ச எழுத்தளவு",
    textStyles: "எழுத்து ஸ்டைல்கள்",
    outline: "வெளிக்கோடு",
    shadow: "நிழல்",
    uppercase: "பெரிய எழுத்துகள்",
    showBox: "அட்டை காட்டு",
    showBorder: "பார்டர் காட்டு",
    lineWrap: "வரி மடிப்பு",
    greenScreenMode: "க்ரீன் ஸ்கிரீன் முறை",
    presentationBackground: "காட்சி பின்னணி",
    remoteControl: "ரிமோட் கண்ட்ரோல்",
    appVersion: "செயலி பதிப்பு",
    aboutApp: "செயலியைப் பற்றி",
    readerBox: "வாசிப்பு அட்டை காட்டு",
    readerBoxDesc: "ஒவ்வொரு வசனத்திற்கும் கண்ணாடி அட்டை காட்டு",
    keepAwake: "திரை தூக்கமின்மை",
    keepAwakeDesc: "வாசிக்கும் போது திரை அணையாமல் இருக்கும்",
    tamilKeyboard: "தமிழ் விசைப்பலகை",
    tamilKeyboardDesc: "தேடலில் தமிழ் விசைப்பலகையை திற",
    backgroundType: "பின்னணி வகை",
    image: "படம்",
    gradient: "நிறச்சரிவு",
    custom: "தனிப்பயன்",
    dataManagement: "தரவு மேலாண்மை",
    exportData: "காப்புப்பிரதி எடு",
    importData: "காப்புப்பிரதி ஏற்று",
    importSuccess: "தரவு வெற்றிகரமாக ஏற்றப்பட்டது!",
    importError: "தரவை ஏற்றுவதில் தோல்வி. கோப்பை சரிபார்க்கவும்.",
  },
  en: {
    home: "Home",
    search: "Search",
    settings: "Settings",
    keywords: "Tamil Bible, Bible in Tamil, Tamil Christian app, Bible verses, Tanglish Bible search, Tamil scripture, Tamil Bible online, Tamil Bible reading, Bible study Tamil, Tamil Bible study tools, Tamil Bible Premium, Tamil Bible Presentation, Church Bible Display Tamil",
    tamilBible: "Tamil Bible",
    richReader: "A rich dark reading experience",
    homeIntro:
      "Choose a testament, open a book, and continue reading with a calmer premium UI on mobile and desktop.",
    tanglishSearch: "Tanglish Search",
    mobileFriendly: "Mobile Friendly",
    readerSettings: "Reader Settings",
    library: "Library",
    chooseStart: "Choose where you want to begin",
    books: "Books",
    testament: "Testament",
    oldTestament: "Old Testament",
    newTestament: "New Testament",
    oldDesc: "History, prophecy, psalms, and wisdom writings",
    newDesc: "Gospels, apostles, letters, and revelation",
    globalSearch: "Global Search",
    searchTitle: "Books, verses, and Tanglish in one place",
    searchIntro:
      "Search book names and verses using Tamil, English, or Tanglish spelling.",
    searchPlaceholder: "Search book or verse...",
    verses: "Verses",
    typeToSearch:
      "Type a verse, book name, or Tanglish phrase to begin searching.",
    chapters: "Chapters",
    selectChapter: "Select a chapter to continue reading.",
    reading: "Reading",
    navigator: "Navigator",
    chapter: "Chapter",
    verse: "Verse",
    prev: "Prev",
    next: "Next",
    share: "Share",
    close: "Close",
    cancel: "Cancel",
    save: "Save",
    readingSetup: "Reading Setup",
    settingsTitle: "Settings",
    settingsIntro:
      "Adjust typography, spacing, appearance, and the UI language to match your reading style.",
    resetSettings: "Reset Settings",
    typography: "Typography",
    typographyIntro: "Make reading calmer and easier to follow.",
    advancedPresentation: "Advanced Presentation",
    advancedPresentationIntro: "Add VerseView-style controls for OBS, stage screen, and casting layouts.",
    screenSetup: "Screen Setup",
    enableMainPresentation: "Enable Main Presentation",
    enableStagePresentation: "Enable Stage Presentation",
    mainPresentationScreen: "Main Presentation Screen",
    stageviewScreen: "Stageview Screen",
    mainPresentationScreenSetup: "Main Presentation Screen Setup",
    stageviewScreenSetup: "Stageview Screen Setup",
    presets: "Presets",
    maximumFontSize: "Maximum Font Size",
    stageScreenStyle: "Stage Screen Style",
    windowView: "Window View",
    smallWindow: "Small Window",
    greenScreen: "Green Screen",
    message: "Message",
    showMessage: "Show Message",
    clearMessage: "Clear Message",
    previewPanel: "Preview",
    backgroundImage: "Background Image",
    logoImage: "Logo Image",
    motionBackground: "Motion Background",
    stillBackground: "Still Background",
    textColor: "Text Color",
    overlayColor: "Overlay Color",
    screenOne: "Screen 1 → 1536x864",
    screenTwo: "Screen 2 → 1920x1080",
    fullScreenHorizontal: "Full screen - Horizontal",
    fullScreenPrimary: "Full Screen - Primary",
    enableTransition: "Enable Transition",
    enableOutline: "Enable Outline",
    enableShadow: "Enable Shadow",
    enableUppercase: "Enable Uppercase",
    enableBorder: "Enable Border",
    enableBox: "Enable Box",
    enableHeaderBox: "Enable Header Box",
    enableLineWrap: "Enable Line Wrap",
    hideStanzaNumber: "Hide Stanza Number",
    showLyricsInTwoLines: "Show Verse in Two Lines",
    keepPresentationWindowOnTop: "Keep Presentation Window on Top",
    showDateAndTime: "Show Date and Time",
    showVerseviewLogo: "Show Tamil Bible Premium Logo",
    showCustomLogo: "Show Custom Logo",
    uploadLogo: "Upload Logo",
    removeLogo: "Remove Logo",
    textOne: "Text 1",
    textTwo: "Text 2",
    overlay: "Overlay",
    stars: "Stars",
    waves: "Waves",
    particles: "Particles",
    aurora: "Aurora",
    embers: "Embers",
    halo: "Halo",
    mist: "Mist",
    fontSize: "Font Size",
    lineSpacing: "Line Spacing",
    textAlign: "Text Align",
    readingCard: "Reading Card",
    readingCardIntro: "Control how strong the reading card appears.",
    cardOpacity: "Card Opacity",
    readerWidth: "Reader Width",
    showReference: "Show Reference",
    yes: "Yes",
    no: "No",
    customBackground: "Custom Background",
    customBackgroundIntro: "Upload your own image to use in the reader.",
    imageUrl: "Image URL",
    useImageLink: "Use Image Link",
    uploadImage: "Upload Image",
    removeImage: "Remove Image",
    applyNow: "Apply Now",
    livePreview: "Live Preview",
    previewVerse: "The Lord is my shepherd; I shall not want.",
    previewVerseEnglish: "The Lord is my shepherd; I shall not want.",
    previewRef: "Psalm 23:1",
    installApp: "Install App",
    installAppIntro:
      "Install this website like a standalone app on mobile or desktop.",
    installNow: "Install Now",
    installed: "Already Installed",
    installHelp:
      "If the button is unavailable, use your browser menu and choose Install App or Add to Home Screen.",
    installBannerTitle: "Install this Bible as an app",
    installBannerText: "Save it to your home screen and open it like native software.",
    imageBackgrounds: "Image Backgrounds",
    imageBackgroundsIntro: "Choose a photo background for the reader.",
    motionBackgroundsIntro: "Choose an animated motion background for the reader.",
    gradientBackgrounds: "Gradient Backgrounds",
    gradientBackgroundsIntro: "Use a softer simplified reader background.",
    language: "Language",
    languageIntro: "Switch the navbar and interface labels.",
    tamil: "Tamil",
    english: "English",
    tamilEnglish: "Tamil + English",
    left: "Left",
    center: "Center",
    justify: "Justify",
    openBook: "Open Book",
    verseOfDay: "Verse of the Day",
    recentReading: "Recent Reading",
    bookmarksTitle: "Bookmarks",
    favoritesTitle: "Favorites",
    highlightsTitle: "Highlights",
    notesTitle: "Notes",
    noItemsYet: "Nothing saved here yet.",
    bookmark: "Bookmark",
    favorite: "Favorite",
    highlight: "Highlight",
    autoScroll: "Auto Scroll",
    pauseScroll: "Pause Scroll",
    note: "Note",
    chapterBookmark: "Bookmark Chapter",
    notePrompt: "Write your private note for this verse.",
    openVerse: "Open Verse",
    openChapter: "Open Chapter",
    savedNote: "Saved Notes",
    savedHighlight: "Highlighted Verses",
    savedFavorite: "Favorite Verses",
    savedBookmark: "Saved Places",
    presentation: "Presentation",
    stageView: "Stage View",
    mainDisplay: "Main Display",
    stageDisplay: "Stage Display Settings",
    enableMainDisplay: "Enable Main Display",
    enableStageDisplay: "Enable Stage Display",
    screenChoice: "Choose Screen",
    maxFontSize: "Maximum Font Size",
    textStyles: "Text Styles",
    outline: "Outline",
    shadow: "Shadow",
    uppercase: "Uppercase",
    showBox: "Show Box",
    showBorder: "Show Border",
    lineWrap: "Auto Line Wrap",
    greenScreenMode: "Green Screen Mode",
    presentationBackground: "Display Background",
    remoteControl: "Remote Control",
    appVersion: "App Version",
    aboutApp: "About App",
    readerBox: "Reading Card",
    readerBoxDesc: "Show a glass card behind each verse",
    keepAwake: "Keep Screen On",
    keepAwakeDesc: "Prevent screen sleep while reading",
    tamilKeyboard: "Tamil Keyboard",
    tamilKeyboardDesc: "Open Tamil keyboard in search",
    backgroundType: "Background Type",
    image: "Image",
    gradient: "Gradient",
    custom: "Custom",
    dataManagement: "Data Management",
    exportData: "Export Backup",
    importData: "Import Backup",
    importSuccess: "Data imported successfully!",
    importError: "Failed to import data. Please check the file.",
  },
};

export function getUIText(language = "ta") {
  return uiText[language] || uiText.ta;
}
